from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from ocr_kb.ingest.batch_builder import BatchItem, build_batch
from ocr_kb.ingest.loader import SUPPORTED_SUFFIXES
from ocr_kb.model import OcrRequest, run_enrichment, run_ocr
from ocr_kb.prompts import (
    IMAGE_FIGURE_PROMPT,
    GLM_OCR_HTML_PROMPT,
    GLM_OCR_PROMPT,
    format_cleanup_prompt,
    format_key_points_prompt,
    format_summary_prompt,
    format_tags_prompt,
)
from ocr_kb.settings import Settings

Mode = Literal["text", "html"]


@dataclass
class PageResult:
    source_path: Path
    page_number: int
    text: str
    mode: Mode
    chunk_index: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    key_points: str | None = None
    summary: str | None = None
    enriched_metadata: str | None = None
    generated_tags: str | None = None  # auto-generated by enrichment when enabled


@dataclass
class FileResult:
    source_path: Path
    pages: list[PageResult] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    @property
    def succeeded(self) -> bool:
        return bool(self.pages)

    @property
    def full_text(self) -> str:
        return "\n\n".join(p.text for p in self.pages)


def _prompt_for_mode(mode: Mode) -> str:
    return GLM_OCR_HTML_PROMPT if mode == "html" else GLM_OCR_PROMPT


def _chunk_text(text: str, chunk_size: int, overlap: int) -> list[str]:
    """Split text at paragraph (or sentence) boundaries into overlapping chunks.

    Returns a single-element list when text is shorter than chunk_size or
    chunk_size <= 0 (i.e., chunking is disabled).
    """
    if chunk_size <= 0 or len(text) <= chunk_size:
        return [text]

    # Normalise line endings so \r\n and \r behave like \n
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Build a list of fine-grained units.
    # Strategy: split on double newlines (paragraph breaks), then further split
    # any unit that is still larger than chunk_size on sentence endings.
    # This handles both well-formatted documents and PDF text-layer output that
    # uses only single \n line endings.
    raw_paragraphs = [p.strip() for p in re.split(r"\n\n+", text) if p.strip()]
    units: list[str] = []
    for para in raw_paragraphs:
        if len(para) > chunk_size:
            # Paragraph too large — split into sentences
            sents = re.split(r'(?<=[.!?])\s+', para)
            units.extend(s.strip() for s in sents if s.strip())
        else:
            units.append(para)
    if not units:
        return [text]

    chunks: list[str] = []
    start = 0

    while start < len(units):
        end = start
        length = 0
        while end < len(units):
            length += len(units[end]) + 1  # +1 for separator
            if length > chunk_size and end > start:
                break
            end += 1
        if end == start:
            end = start + 1  # single unit larger than chunk_size

        chunk = " ".join(units[start:end])
        # Prepend a tail from the previous chunk for context overlap.
        if chunks and overlap:
            tail = chunks[-1][-overlap:]
            chunk = tail + " " + chunk
        chunks.append(chunk)
        start = end

    return chunks or [text]


def _process_item(
    item: BatchItem,
    settings: Settings,
    mode: Mode,
    *,
    extract_key_points: bool,
    extract_summary: bool,
    gemma_enrichment: bool,
    vision_model: str | None = None,
    text_model: str | None = None,
) -> PageResult:
    backend = settings.model_backend

    if item.needs_ocr:
        if backend == "gemma_only":
            raise ValueError(
                f"model_backend='gemma_only' cannot process vision file "
                f"'{item.source_path.name}'. Use 'hybrid' or 'glm_only'."
            )
        assert item.image is not None
        resp = run_ocr(
            OcrRequest(image=item.image, prompt=_prompt_for_mode(mode)),
            settings,
            vision_model=vision_model,
        )
        page = PageResult(
            source_path=item.source_path,
            page_number=item.page_number,
            text=resp.text,
            mode=mode,
            prompt_tokens=resp.prompt_tokens,
            completion_tokens=resp.completion_tokens,
        )
    else:
        assert item.text_content is not None
        page = PageResult(
            source_path=item.source_path,
            page_number=item.page_number,
            text=item.text_content,
            mode=mode,
        )

    if not page.text.strip():
        return page

    # Describe embedded images (figures, charts, diagrams) and append to page text.
    # Skipped in glm_only mode (no text model available) and when there are no images.
    if item.embedded_images and backend != "glm_only":
        figure_parts: list[str] = []
        for i, emb_img in enumerate(item.embedded_images, 1):
            try:
                resp = run_ocr(
                    OcrRequest(image=emb_img, prompt=IMAGE_FIGURE_PROMPT),
                    settings,
                    vision_model=vision_model,
                )
                desc = resp.text.strip()
                if desc:
                    figure_parts.append(f"[Figure {i}]: {desc}")
            except Exception:
                pass
        if figure_parts:
            page.text += "\n\n" + "\n\n".join(figure_parts)

    # glm_only: vision extraction only — no text enrichment calls
    if backend == "glm_only":
        return page

    if extract_key_points:
        page.key_points = run_enrichment(
            format_key_points_prompt(page.text), settings, text_model=text_model
        )

    if extract_summary:
        page.summary = run_enrichment(
            format_summary_prompt(page.text), settings, text_model=text_model
        )

    if gemma_enrichment:
        page.enriched_metadata = run_enrichment(
            format_cleanup_prompt(page.text), settings, text_model=text_model
        )
        page.generated_tags = run_enrichment(
            format_tags_prompt(page.text), settings, text_model=text_model
        )

    return page


def process_file(
    path: Path,
    settings: Settings,
    *,
    mode: Mode = "text",
    page_range: str | None = None,
    extract_key_points: bool = False,
    extract_summary: bool = False,
    gemma_enrichment: bool | None = None,
    vision_model: str | None = None,
    text_model: str | None = None,
    on_page: Callable[[int, int], None] | None = None,
) -> FileResult:
    """Process a single file and return one PageResult per page.

    *vision_model* / *text_model* override the model names from settings for
    this call only — useful for per-ingest model selection from the CLI or MCP.
    *on_page* is called as ``on_page(current_page, total_pages)`` after each page
    completes — useful for driving progress bars.
    """
    result = FileResult(source_path=path)
    do_enrich = settings.enable_gemma_enrichment if gemma_enrichment is None else gemma_enrichment
    try:
        batch = build_batch(path, settings, page_range)
    except Exception as exc:
        result.errors.append(f"Failed to load {path.name}: {exc}")
        return result

    total = len(batch)
    for i, item in enumerate(batch, start=1):
        try:
            page = _process_item(
                item,
                settings,
                mode,
                extract_key_points=extract_key_points,
                extract_summary=extract_summary,
                gemma_enrichment=do_enrich,
                vision_model=vision_model,
                text_model=text_model,
            )
            if settings.chunk_size > 0 and len(page.text) > settings.chunk_size:
                for ci, chunk_text in enumerate(
                    _chunk_text(page.text, settings.chunk_size, settings.chunk_overlap), 1
                ):
                    result.pages.append(PageResult(
                        source_path=page.source_path,
                        page_number=page.page_number,
                        text=chunk_text,
                        mode=page.mode,
                        chunk_index=ci,
                        key_points=page.key_points if ci == 1 else None,
                        summary=page.summary if ci == 1 else None,
                        enriched_metadata=page.enriched_metadata if ci == 1 else None,
                        generated_tags=page.generated_tags if ci == 1 else None,
                    ))
            else:
                result.pages.append(page)
        except Exception as exc:
            result.errors.append(f"Page {item.page_number}: {exc}")
        if on_page:
            on_page(i, total)

    return result


def process_path(
    path: Path,
    settings: Settings,
    *,
    mode: Mode = "text",
    page_range: str | None = None,
    extract_key_points: bool = False,
    extract_summary: bool = False,
    gemma_enrichment: bool | None = None,
    vision_model: str | None = None,
    text_model: str | None = None,
    on_page: Callable[[int, int], None] | None = None,
) -> list[FileResult]:
    """Process a single file or every supported file under a directory."""
    if path.is_file():
        return [
            process_file(
                path,
                settings,
                mode=mode,
                page_range=page_range,
                extract_key_points=extract_key_points,
                extract_summary=extract_summary,
                gemma_enrichment=gemma_enrichment,
                vision_model=vision_model,
                text_model=text_model,
                on_page=on_page,
            )
        ]

    files = sorted(
        f
        for f in path.rglob("*")
        if f.is_file() and f.suffix.lower() in SUPPORTED_SUFFIXES
    )
    return [
        process_file(
            f,
            settings,
            mode=mode,
            page_range=page_range,
            extract_key_points=extract_key_points,
            extract_summary=extract_summary,
            gemma_enrichment=gemma_enrichment,
            vision_model=vision_model,
            text_model=text_model,
            on_page=on_page,
        )
        for f in files
    ]
